### ISSUE TITLE
why the possibility to send the error is not documented ?

### ISSUE THREAD

**Issue by ma0dubois** [goksagun/elastic-apm-bundle#2]
Hi,

Just a question, why not talk about the possibility to send the error ?
just add this to the elastic_apm.yml file:

```yaml
parameters:
    elastic_apm:
        enabled: true
        appName: 'APPtest' #Name of this application, Required
        appVersion: '1' #Application version, Default: ''
        # serverUrl: "http://%env(ELASTICAPM_SERVERURL)%" #APM Server Endpoint, Default: 'http://127.0.0.1:8200'
        serverUrl: "http://yourhost:8200" #APM Server Endpoint, Default: 'http://127.0.0.1:8200'
        secretToken: null #Secret token for APM Server, Default: null
        errors:
            enabled: true
            exclude:
                status_codes: ~
                exceptions: ~
```

There is a reason for that ?
